name: pos_scan
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  
 
  
  http: ^1.2.2
  shared_preferences: ^2.3.3
  path_provider: ^2.0.11
  csv: ^5.0.1
  permission_handler: ^11.0.0
  file_selector: ^0.9.0
  flutter_launcher_icons: ^0.10.0
  audioplayers: ^6.1.0
  dropdown_button2: ^2.0.0
  dropdown_search: ^5.0.2
   #  LOCAL PATCHED PACKAGE
  flutter_barcode_scanner:
    path: ./flutter_barcode_scanner1
  flutter_inappwebview: ^6.1.5
 
 
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Auctech-logo.png
    - assets/auctech.mp3
    - assets/beep.mp3
    - assets/wrong.mp3
    - assets/logo-black-.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo-black-.jpg"


